# Generated by Django 3.1.4 on 2020-12-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_names', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=10)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Pricing',
            },
        ),
    ]
