# Generated by Django 3.1.4 on 2020-12-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('appointment_time', models.CharField(choices=[('1', '9 am to 10 am'), ('2', '10:30 am to 11:30 am'), ('3', '11:30 am to 12:30 pm'), ('4', '12:30 am to 1:30 pm'), ('5', '1:30 pm to 2:30 pm'), ('6', '2:30 pm to 3:30 pm'), ('7', '3:30 pm to 4:30 pm'), ('8', '4:30 pm to 5:30 pm')], max_length=50)),
                ('choose_date', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=50)),
                ('your_message', models.TextField()),
            ],
        ),
    ]
