# Generated by Django 3.1.4 on 2021-01-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210116_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='choose_date',
            field=models.CharField(choices=[('Choose Your Date', 'Choose Your Date'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Choose Your Date', max_length=50),
        ),
    ]
