# Generated by Django 3.1.4 on 2021-01-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210117_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='choose_date',
            field=models.CharField(choices=[('choose Your Date', 'Choose Your Date'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='Choose Your Date', max_length=50),
        ),
    ]
