# Generated by Django 3.1.4 on 2021-01-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210117_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.CharField(choices=[('First Choice appointment time', 'First Choice appointment time'), ('9 am to 10 am', '9 am to 10 am'), ('10:30 am to 11:30 am', '10:30 am to 11:30 am'), ('11:30 am to 12:30 pm', '11:30 am to 12:30 pm'), ('12:30 am to 1:30 pm', '12:30 am to 1:30 pm'), ('1:30 pm to 2:30 pm', '1:30 pm to 2:30 pm'), ('2:30 pm to 3:30 pm', '2:30 pm to 3:30 pm'), ('3:30 pm to 4:30 pm', '3:30 pm to 4:30 pm'), ('4:30 pm to 5:30 pm', '4:30 pm to 5:30 pm')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='choose_date',
            field=models.CharField(choices=[('Choose Your Date', 'Choose Your Date'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Choose Your Date', max_length=50),
        ),
    ]
